version: '3'

services:
  api:
    build: ./
    ports:
      - 3000:3000
    container_name: ticketAPI
    environment:
      - DB_HOST=db

  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ticketDB
    users: "503"
    volumes:
      - /data
